#this config file triggers all three dag layers for the etl spec 
dag: 
  dag_id: agency_mstr_dag
  schedule_interval: timedelta(days=1)
  staging_dags:
  -agency_stg_load
  transform_dags:
  -agency_transform_load
default_args:
  depends_on_past: false
  owner: airflow
  retries: 3
  retry_delay: timedelta(minutes=5)
  start_date: days_ago(1)
